export const queryKeys = {
  clients: (params = {}) => ['clients', params],
  client: (clientId) => ['client', clientId],
  clientRelations: (clientId) => ['clientRelations', clientId],
  calls: (params = {}) => ['calls', params],
  call: (callId) => ['call', callId],
  events: (params = {}) => ['events', params],
  event: (eventId) => ['event', eventId],
  transactions: (params = {}) => ['transactions', params],
  transactionsAll: ['transactions', {}],
  partyTransactions: (params = {}) => ['party-transactions', params],
  partyTransactionsAll: ['party-transactions', {}],
  statistics: (params = {}) => ['statistics', params],
  services: (params = {}) => ['services', params],
  service: (serviceId) => ['service', serviceId],
  users: (params = {}) => ['users', params],
  user: (userId) => ['user', userId],
  tariffs: (params = {}) => ['tariffs', params],
  tariff: (tariffId) => ['tariff', tariffId],
  siteSettings: ['siteSettings'],
  loggedUser: ['loggedUser'],
}
