export const eventKeys = {
  clientId: 'Клиент',
  eventDate: 'Дата и время начала',
  dateEnd: 'Дата и время завершения',
  address: 'Адрес',
  status: 'Статус',
  servicesIds: 'Услуги',
  contractSum: 'Договорная сумма',
  waitDeposit: 'Ждем задаток',
  depositDueAt: 'Дата ожидания задатка',
  depositExpectedAmount: 'Сумма задатка',
  description: 'Комментарий',
  eventType: 'Что за событие',
  additionalEvents: 'Доп. события',
  financeComment: 'Комментарий по финансам',
  contractLinks: 'Ссылки на договора',
  invoiceLinks: 'Ссылки на счета',
  receiptLinks: 'Ссылки на чеки',
  actLinks: 'Ссылки на акты',
  isTransferred: 'Передано коллеге',
  colleagueId: 'Коллега',
  otherContacts: 'Прочие контакты',
  calendarImportChecked: 'Проверка мероприятия',
  calendarSyncError: 'Синхронизация календаря',
}

export const userKeys = {
  firstName: 'Имя',
  secondName: 'Фамилия',
  thirdName: 'Отчество',
  email: 'eMail',
  password: 'Пароль',
  images: 'Фотографии',
  registrationType: 'Тип регистрации',
  phone: 'Телефон',
  whatsapp: 'Whatsapp',
  viber: 'Viber',
  telegram: 'Telegram',
  instagram: 'Instagram',
  vk: 'ВКонтакте',
  tariffId: 'Тариф',
  trialActivatedAt: 'Старт пробного периода',
  trialEndsAt: 'Окончание пробного периода',
  trialUsed: 'Пробный период использован',
  balance: 'Баланс',
  billingStatus: 'Биллинг',
  tariffActiveUntil: 'Тариф активен до',
  nextChargeAt: 'Следующее списание',
  role: 'Роль',
  lastActivityAt: 'Время последней активности',
  prevActivityAt: 'Время предпоследней активности',
  archive: 'В архиве',
  notifications: 'Настройки уведомлений',
  googleCalendar: 'Google Calendar',
}
